version: 0.2
env:
  variables:
    GOPATH: /go
    GOBIN: /go/bin
    ROOTPATH: /go/src/github.com/swoldemi/test-publish-before-package
phases:
  install:
    runtime-versions:
      golang: 1.14
    commands:
      - pip3 install -U aws-sam-cli

  build:
    commands:
      - chmod +x ./publish.sh && ./publish.sh