AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Metadata:
  AWS::ServerlessRepo::Application:
    Name: test-publish-before-package
    Description: Just a test
    Author: Simon Woldemichael
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    HomePageUrl: https://github.com/swoldemi/test-publish-before-package
    SemanticVersion: 1.0.0
    SourceCodeUrl: https://github.com/swoldemi/test-publish-before-package

Resources:
  CognitoCustomDomainLinkExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  TestPublishBeforePackage:
    Type: AWS::Serverless::Function
    Description: Lambda handler for test-publish-before-package
    Properties:
      FunctionName: test-publish-before-package
      Handler: main
      Runtime: go1.x
      MemorySize: 128
      Role: !GetAtt CognitoCustomDomainLinkExecutionRole.Arn
      Timeout: 15

Outputs:
  LambdaFunctionARN:
    Description: CognitoCustomDomainLink Lambda Function ARN
    Value: !GetAtt TestPublishBeforePackage.Arn
